Vagrant.configure("2") do |config|
  config.vm.define "box" do |box|
		box.vm.box = "hashicorp/precise32"
		box.vm.hostname = "lab2-box"
		box.vm.provider "virtualbox" do |virtualbox|
        virtualbox.name="lab2-box"
    end
  config.vm.provision "shell", inline: 
    "sudo sed -i.bak -r 's/(extras|us.archive|us.security|security).(ubuntu|canonical).com/old-releases.ubuntu.com/g' /etc/apt/sources.list"
  config.vm.provision "shell", inline: 
    "sudo apt-get update -y"
  config.vm.provision "shell", inline: 
    "sudo apt-get install -y gdb"
 end
end
